name: Auto Proxy Fetch

on:
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
    push:
        paths:
            - 'src/proxy.ts'

jobs:
    fetch-and-update:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            
        steps:
              - name: Checkout repository
                uses: actions/checkout@v2

              - name: Setup pnpm
                uses: pnpm/action-setup@v4.0.0
                with:
                  version: '9.15.4' # optional
                  dest: '~/setup-pnpm' # required

              - name: Cache pnpm
                uses: actions/cache@v3
                with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                    ${{ runner.os }}-pnpm-

              - name: Install dependencies
                run: pnpm install

              - name: Run proxy fetcher
                run: pnpm run proxy

              - name: Commit and push if there are changes
                run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add proxies.txt
                  git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Update proxy list [skip ci]" && git push)
