name: Auto Proxy Fetch

on:
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
    push:
        paths:
            - 'src/proxy.ts'
jobs:
    fetch-and-update:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            
        steps:
              - name: Checkout repository
                uses: actions/checkout@v2

              - name: Setup pnpm
                uses: pnpm/action-setup@v4.0.0
                with:
                  version: '7.0.0' # optional
                  dest: '~/setup-pnpm' # required

              - name: Check for package.json
                run: ls -la /home/runner/work/proxy-auto-ts/proxy-auto-ts

              - name: Install dependencies
                run: pnpm install