name: Auto Proxy Fetch

on:
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
    push:
        paths:
            - 'src/proxy.ts'

jobs:
    fetch-and-update:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            
        steps:
              - name: Checkout repository
                uses: actions/checkout@v2

              - name: Setup pnpm
                uses: pnpm/action-setup@v4.0.0
                with:
                  version: '9.15.4'

              - name: Cache pnpm
                uses: actions/cache@v3
                with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                    ${{ runner.os }}-pnpm-

              - name: Install dependencies
                run: pnpm install
